# Generated by Django 4.0.1 on 2022-01-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='webinar_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
