# Generated by Django 4.0.1 on 2022-01-10 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='slug',
        ),
    ]
