# Generated by Django 4.0.1 on 2022-01-23 08:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_lesson_webinar_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='user',
        ),
        migrations.AddField(
            model_name='lesson',
            name='isComplete',
            field=models.ManyToManyField(blank=True, related_name='completed_lessons', to=settings.AUTH_USER_MODEL),
        ),
    ]
