# Generated by Django 4.0.1 on 2022-01-23 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_lesson_user_lesson_iscomplete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='isComplete',
            new_name='completed_users',
        ),
    ]
