# Generated by Django 4.0.1 on 2022-01-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_course_slug_lesson_slug_theme_slug_alter_lesson_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='text_file',
            field=models.FileField(blank=True, null=True, upload_to='lessons_files/'),
        ),
    ]
