# Generated by Django 4.0.1 on 2022-01-12 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_lesson_text_lesson_text_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='pictures/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='text_file',
            field=models.FileField(blank=True, null=True, upload_to='lessons_files/', validators=[django.core.validators.FileExtensionValidator(['txt', 'html'])]),
        ),
    ]
