# Generated by Django 4.0.1 on 2022-01-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_course_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='is_last',
            field=models.BooleanField(default=False),
        ),
    ]
